package com.moon.quizdog

class Const {
    val thumbnail = arrayOf(
        R.drawable.afghane,
        R.drawable.akita,
        R.drawable.alsakamalamute,
        R.drawable.americanfitbulterrier,
        R.drawable.apenpinsher,
        R.drawable.biggle,
        R.drawable.bishong,
        R.drawable.bolonez,
        R.drawable.bordercoli,
        R.drawable.borjoy,
        R.drawable.boxer,
        R.drawable.brishellgripen,
        R.drawable.bullterrier,
        R.drawable.burnizmountain,
        R.drawable.canecorso,
        R.drawable.chichu,
        R.drawable.chiwawa,
        R.drawable.chowchow,
        R.drawable.coca,
        R.drawable.comondor,
        R.drawable.cotongdtrar,
        R.drawable.dalmatian,
        R.drawable.englishbuldog,
        R.drawable.englishmastiff,
        R.drawable.goldenretriever,
        R.drawable.grayhound,
        R.drawable.greatdain,
        R.drawable.greatpireniz,
        R.drawable.havanasilk,
        R.drawable.jackrusselterier,
        R.drawable.japernischin,
        R.drawable.jermansheperd,
        R.drawable.kangal,
        R.drawable.kvaliekingchals,
        R.drawable.martiz,
        R.drawable.minidakshunt,
        R.drawable.minipin,
        R.drawable.minishunawger,
        R.drawable.newpundlerand,
        R.drawable.pakiniz,
        R.drawable.papiyong,
        R.drawable.perg,
        R.drawable.pome,
        R.drawable.ravraduddle,
        R.drawable.ravraduretriever,
        R.drawable.rotwhiler,
        R.drawable.russelterier,
        R.drawable.samoyed,
        R.drawable.sapai,
        R.drawable.siva,
        R.drawable.siverianhusky,
        R.drawable.stbernard,
        R.drawable.toyfoxteria,
        R.drawable.toypudle,
        R.drawable.vernesemountaindog,
        R.drawable.weimaraner,
        R.drawable.welsicogi,
        R.drawable.york
    )

    val name = arrayOf(
        "아프간하운드",
        "아키타",
        "알래스카 말라뮤트",
        "아메리칸 핏불 테리어",
        "아펜핀셔",
        "비글",
        "비숑 프리제",
        "볼로네즈",
        "보더콜리",
        "보르조이",
        "복서",
        "브뤼셀 그리핀",
        "불 테리어",
        "버니즈 마운틴",
        "카네 코르소",
        "시츄",
        "치와와",
        "차우차우",
        "코카 스패니얼",
        "코몬도르",
        "꼬동 드 툴레아",
        "달마시안",
        "잉글리쉬 불독",
        "잉글리쉬 마스티프",
        "골든 리트리버",
        "그레이 하운드",
        "그레이트 데인",
        "그레이트 피레니즈",
        "하바나 실크",
        "잭 러셀 테리어",
        "재퍼니스 친",
        "저먼 셰퍼드",
        "캉갈",
        "카발리에 킹 찰스 스패니얼",
        "마티즈",
        "미니어쳐 닥스훈트",
        "미니핀",
        "미니어쳐 슈나우저",
        "뉴펀들랜드",
        "페키니즈",
        "빠삐용",
        "퍼그",
        "포메라니안",
        "래브라도 두들",
        "래브라도 리트리버",
        "로트 와일러",
        "러셀 테리어",
        "사모예드",
        "샤페이",
        "시바",
        "시베리안 허스키",
        "세인트 버나드",
        "토이 폭스테리어",
        "토이 푸들",
        "버나드 마운틴",
        "와이머라너",
        "웰시코기",
        "요크셔테리어"
    )
}